apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace/monitoring-namespace.yaml
  - exporters/node-exporter.yaml
  - exporters/kube-state-metrics.yaml
  - prometheus/prometheus-deployment.yaml
  - alertmanager/alertmanager-deployment.yaml
  - grafana/grafana-deployment.yaml

commonLabels:
  app.kubernetes.io/part-of: observability-stack
  app.kubernetes.io/managed-by: kustomize

namespace: monitoring