apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
  namespace: monitoring
type: Opaque
stringData:
  admin-user: ${GRAFANA_ADMIN_USER:-admin}
  admin-password: ${GRAFANA_ADMIN_PASSWORD:-admin123}