global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'alerts@company.com'
  smtp_auth_username: 'alerts@company.com'
  smtp_auth_password: 'your-app-password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      component: pod
    receiver: 'pod-alerts'
  - match:
      component: node
    receiver: 'infrastructure-alerts'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://webhook-service:5000/webhook'
    send_resolved: true

- name: 'critical-alerts'
  email_configs:
  - to: 'devops-team@company.com'
    subject: 'CRITICAL: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Namespace: {{ .Labels.namespace }}
      Pod: {{ .Labels.pod }}
      Time: {{ .StartsAt }}
      {{ end }}
  slack_configs:
  - api_url: 'YOUR_SLACK_WEBHOOK_URL'
    channel: '#alerts-critical'
    title: 'Critical Alert'
    text: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

- name: 'pod-alerts'
  email_configs:
  - to: 'dev-team@company.com'
    subject: 'Pod Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
    body: |
      {{ range .Alerts }}
      Pod Issue Detected:
      - Alert: {{ .Annotations.summary }}
      - Description: {{ .Annotations.description }}
      - Namespace: {{ .Labels.namespace }}
      - Pod: {{ .Labels.pod }}
      - Container: {{ .Labels.container }}
      - Node: {{ .Labels.node }}
      - Time: {{ .StartsAt }}
      
      Root Cause Analysis:
      1. Check pod logs: kubectl logs {{ .Labels.pod }} -n {{ .Labels.namespace }}
      2. Describe pod: kubectl describe pod {{ .Labels.pod }} -n {{ .Labels.namespace }}
      3. Check events: kubectl get events -n {{ .Labels.namespace }} --sort-by='.lastTimestamp'
      {{ end }}

- name: 'infrastructure-alerts'
  email_configs:
  - to: 'infrastructure-team@company.com'
    subject: 'Infrastructure Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
    body: |
      {{ range .Alerts }}
      Infrastructure Issue:
      - Alert: {{ .Annotations.summary }}
      - Description: {{ .Annotations.description }}
      - Component: {{ .Labels.component }}
      - Node: {{ .Labels.node }}
      - Time: {{ .StartsAt }}
      {{ end }}

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']