apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: observability-stack
  namespace: flux-system
spec:
  interval: 10m
  path: "./manifests"
  prune: true
  sourceRef:
    kind: GitRepository
    name: observability-stack
  validation: client
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: prometheus
      namespace: monitoring
    - apiVersion: apps/v1
      kind: Deployment
      name: grafana
      namespace: monitoring
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: observability-stack
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: https://github.com/adarshvyas99/multicloud_k8s-observability